title: "第6話 「謎の漫画」"
date: "2025-08-26"
tags: [謎, ミステリー]
pages:
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-06/001.png"
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-06/002.png"
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-06/003.png"
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-06/004.png"
