title: "第5話 「色々」"
date: "2025-08-25"
tags: [雑談, 日常]
pages:
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-05/001.png"
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-05/002.png"
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-05/003.png"
  - "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-05/004.png"
