title: 第2話「二歩目」
date: 2025-08-22
tags: [冒険, ファンタジー]
pages:
  - https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-02/g24050501.png
  - https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/comics/my-manga/episode-02/g24052301.png
