- title: "キャンプ"
  date: "2024-07-15"
  tags: ["オリジナル", "キャンプ"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0001.png"

- title: "I'm blue man"
  date: "2024-07-16"
  tags: ["オリジナル", "自己紹介"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0002.png"

- title: "釣り"
  date: "2024-07-17"
  tags: ["オリジナル", "釣り"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0003.png"

- title: "ドライブ"
  date: "2024-07-18"
  tags: ["オリジナル", "ドライブ"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0004.png"

- title: "乗馬"
  date: "2024-07-19"
  tags: ["オリジナル", "乗馬"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0005.png"

- title: "いもむし"
  date: "2024-07-20"
  tags: ["オリジナル", "いもむし"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0006.png"

- title: "ペンギンとアイス"
  date: "2024-07-21"
  tags: ["オリジナル", "ぺんぎん", "アイス"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0007.png"

- title: "休憩中"
  date: "2024-07-22"
  tags: ["オリジナル", "ペンギン", "休憩"]
  url: "https://comic-site-v1-images-lgpq.s3.ap-northeast-1.amazonaws.com/illustrations/0008.png"
